<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Incorrect INN checksum' => 'Неверная контрольная сумма ИНН',
    'Incorrect INN length' => 'Неверная длина ИНН',
    'Incorrect OGRN checksum' => 'Неверная контрольная сумма ОГРН/ОРГНИП',
    'Incorrect OGRN length' => 'Неверная длина ОГРН/ОГРНИП',
    'Incorrect OGRN registration attribution flag' => 'Неверный признак отнесения ОГРН/ОГРНИП',
    'Incorrect OGRN registration year' => 'Неверный год регистрации ОГРН/ОГРНИП',
];
